set-option -g prefix C-s
unbind C-b
bind C-s send-prefix

# Configurations
set -g mouse on

set-window-option -g mode-keys vi

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Split panes with intuitive keys
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind %
unbind '"'

# Ask for window name on creation
bind c command-prompt -p "Window name:" "new-window -n '%%'"

# Resize panes with Shift+Ctrl+hjkl (no prefix required)
bind-key -n C-S-h resize-pane -L 5
bind-key -n C-S-j resize-pane -D 5
bind-key -n C-S-k resize-pane -U 5
bind-key -n C-S-l resize-pane -R 5

set-option -g status-position top

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @catppuccin_window_status_style 'rounded'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @resurrect-save 's'
set -g @resurrect-restore 'R'
#set -g @plugin 'catppuccin/tmux#v2.1.3'

# Configuration of vim-tmux-navigator
set -g @vim_navigator_mapping_left "C-Left C-h"  # use C-h and C-Left
set -g @vim_navigator_mapping_right "C-Right C-l"
set -g @vim_navigator_mapping_up "C-k"
set -g @vim_navigator_mapping_down "C-j"
set -g @vim_navigator_mapping_prev ""  # removes the C-\ binding

# Configuration of plugins
# set -g @catppuccin_flavor 'mocha'
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application} #{E:@catppuccin_status_session}"

set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_current_text " #W"

run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux

run '~/.tmux/plugins/tpm/tpm'

set -g status-style bg=default

