set-option -g prefix C-s
unbind C-b
bind C-s send-prefix

# Passing through C-o to tmux
bind o send-keys C-o


# Configurations
set -g mouse on
set -g extended-keys on
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

set-window-option -g mode-keys vi

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Split panes with intuitive keys
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind %
unbind '"'

# Resize panes with Shift+Ctrl+hjkl (no prefix required)
bind-key -n C-S-h if -F '#{@pane-is-vim}' 'send-keys C-S-h' 'resize-pane -L 1'
bind-key -n C-S-j if -F '#{@pane-is-vim}' 'send-keys C-S-j' 'resize-pane -D 1'
bind-key -n C-S-k if -F '#{@pane-is-vim}' 'send-keys C-S-k' 'resize-pane -U 1'
bind-key -n C-S-l if -F '#{@pane-is-vim}' 'send-keys C-S-l' 'resize-pane -R 1'

set-option -g status-position top

# Bindings for popups
bind z display-popup -w 60% -h 70% -d "#{pane_current_path}"
bind C-a display-popup -w 50% -h 90% -d "#{pane_current_path}" -x R -y C "opencode"
bind C-A display-popup -w 50% -h 90% -d "#{pane_current_path}" -x R -y C "opencode -c"
bind c display-popup -E -w 50% -h 10% -d "#{pane_current_path}" "bash -i -c 'read -p \"Window name: \" name; tmux new-window -n \$name -c \"#{pane_current_path}\"'"
bind C-n display-popup -E -w 50% -h 10% 'bash -i -c "read -p \"Session name: \" name; tmux new-session -d -s \$name && tmux switch-client -t \$name"'
bind C-j display-popup -E -w 30% -h 30% "tmux list-sessions | sed -E 's/:.*$//' | grep -v \"^$(tmux display-message -p '#S')\$\" | fzf --reverse | xargs tmux switch-client -t"

bind a split-window -h -p 50 -c "#{pane_current_path}" "opencode --port"
bind A split-window -h -p 50 -c "#{pane_current_path}" "opencode -c --port"

#set -g pane-border-style "bg=default"
#set -g pane-active-border-style "bg=default,fg=#b4befe"

# Bindings for copy mode with Vi keybindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi V send-keys -X select-line
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"

# improve colors
set -g default-terminal "tmux-256color"
set -as terminal-overrides ",*:RGB"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @catppuccin_window_status_style 'rounded'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @resurrect-save 's'
set -g @resurrect-restore 'R'
set -g @continuum-restore 'on'
set -g @plugin 'parwest/tmux-spoony'
#set -g @plugin 'catppuccin/tmux#v2.3.0'

#tmux-jot
set -g @jot-dir "~/.local/share/tmux-jot"
set -g @jot-editor "nvim"
set -g @plugin 'szymonwilczek/tmux-jot'

# Configuration of vim-tmux-navigator
set -g @vim_navigator_mapping_left "C-Left C-h"  # use C-h and C-Left
set -g @vim_navigator_mapping_right "C-Right C-l"
set -g @vim_navigator_mapping_up "C-k"
set -g @vim_navigator_mapping_down "C-j"
set -g @vim_navigator_mapping_prev ""  # removes the C-\ binding

# Configuration of plugins
set -g @catppuccin_flavor 'mocha'
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application} #{E:@catppuccin_status_session}"

set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_current_text " #W"

run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux

run '~/.tmux/plugins/tpm/tpm'

set -g status-style bg=default
